### PR TITLE
Add implementation of `Walker` for `&'a mut W` where `W: Walker`

### PR DESCRIPTION
**Pull request by mitchmindtree**
I just came across the desire for this working on a geometry graph
downstream that uses daggy. This is akin to the `Iterator`
implementation for `&'a mut I` where `I: Iterator`.

### CODE REVIEW

**Comment by bluss** [comment]
Lol, #113  just prepping for the next release.. :hourglass_flowing_sand: :slightly_smiling_face:

**Comment by mitchmindtree** [comment]
Ahhhhhh :man_facepalming: didn't even think to check for such a wee PR hah! I also didn't realise about the breakage. Happy for this to be closed in favour of #113 if you'd like :)

**Comment by bluss** [comment]
Note the date on that old PR. We need some action..

**Comment by bluss** [comment]
Thanks <3

**Pull request closed without merging**
