### PR TITLE
Generalize `IntoWeightedEdge` from `Copy` to `Clone`

### PR DESCRIPTION
**Pull request by pthariensflame**

### CODE REVIEW

**Comment by bluss** [comment]
Hm why is this? The ix types are always Copy

**Comment by pthariensflame** [comment]
It's a first step towards a plan to generalize the whole library in the same way.  Is that not desired?

**Comment by bluss** [comment]
I don't think so, I went from clone to copy for `GraphBase::NodeId` in 0.3 or 0.4.

**Comment by pthariensflame** [comment]
Oh, ok!  I'll close this then.  :)

**Pull request closed without merging**
