### PR TITLE
Derive Serialize and Deserialize for some common types

### PR DESCRIPTION
**Pull request by fintelia**
A first pass at addressing https://github.com/bluss/petgraph/issues/139.

### CODE REVIEW

**Comment by bluss** [comment]
Hi, thank you for this.

Deriving serialization traits is convenient but it also exposes all private fields, so we lose encapsulation. Do you see where I'm coming from? Say if we want to make changes to private fields of StableGraph, then it's a breaking change. This is the reason I think the graphs need deliberate ser/de implementations.

**Comment by bluss** [comment]
See also #142.

**Comment by fintelia** [comment]
That makes a lot of sense

**Comment by bluss** [comment]
I even think Graph and StableGraph should have the same serialized repr. (Of course something discovered during implementation could derail this goal.)

**Comment by bluss** [comment]
Please see issue #139 for discussing a design

**Comment by bluss** [comment]
serde support for Graph, StableGraph has been merged in #166

**Pull request closed without merging**
